### ISSUE TITLE
Need a new release tagged for 13.0 compatibility change

### ISSUE THREAD

**Issue by mikebobadilla** [apparentlymart/terraform-credentials-env#3]
I saw there was a fix about 4 months ago, but no release since September 2019.

Can you tag a new release please?

**Comment by jralph** [comment]
Any news on this?

**Comment by jralph** [comment]
@apparentlymart @alisdair

**Comment by hikerspath** [comment]
Any updates?

**Comment by apparentlymart** [comment]
Hi all,

The Terraform team at HashiCorp is planning to integrate essentially the same functionality as this credentials helper into the forthcoming Terraform CLI v1.2.0 release. 

At that point I'm planning to archive this repository, although I don't plan to delete it completely in order to create some continuity. However, it is unlikely I'll have time to prepare a new release of the helper plugin before then, so I'm going to close this. If anyone does need the changes added since the previous release, building from source code is your second best option if upgrading to CLI v1.2 isn't possible (yet).

Sorry for the long delay in answering... the hazard of spare time projects. 😖
