### ISSUE TITLE
Pass credentials as file instead of ENV? 

### ISSUE THREAD

**Issue by flickerfly** [apparentlymart/terraform-credentials-env#5]
In some environments, the ability to, if gaining access to the running environment, see the password by listing our the environment variables, `env`, means this method is not allowed. Instead, we can pass a file location as the variable or just dump the details into a known file location. 

Would you consider looking in a known location for the credentials? A format like credentials.tfrc.json might make sense. 

```
{
  "credentials": {
    "terraform.my-enterprise.dev": {
      "token": "some long token string"
    }
  }
}
```

Especially nice would be allowing the use to specify the location. Maybe specifying a location for a file would be what triggers the file instead of env based credential lookup?

**Comment by apparentlymart** [comment]
Hi @flickerfly,

I'm not planning to increase the scope of _this_ credentials helper, because its focus is directly on the idea of using environment variables, but I've no problem with you using the code in this repository as the basis of another credentials helper if you'd like.  (The license already permits, of course, regardless of what I might say about it!)

The idea of Terraform credentials helpers is that each one is small and focused only on a particular use-case, and so introducing a new one that's focused on reading files from disk seems within that spirit.

With that said, if you intend to just use the `credentials.tfrc.json` format itself then I wonder if that credentials helper would then do anything that Terraform itself can't already do. If you can edit the CLI configuration to configure a credentials helper then you can also edit it to include a direct `credentials` block, so unless you want to do something different/unusual with the file format you'd use here I'd probably just use the built-in credentials file functionality directly and not configure a credentials helper in that case. No harm in writing a credentials helper for it if you have a use-case where that's helpful, though!
