### ISSUE TITLE
Request for release with `Respond with empty object if no credentials found` fix

### ISSUE THREAD

**Issue by ChristianMercer** [apparentlymart/terraform-credentials-env#8]
It would be helpful for future users/automated workflows if the latest released archives included this fix.

**Comment by apparentlymart** [comment]
Hi @ChristianMercer,

HashiCorp has decided to upstream the functionality of this credentials helper into Terraform CLI itself as of the forthcoming Terraform v1.2.0, and so I'm not intending to maintain this any further and intend to archive it with a message to that effect once v1.2.0 reaches its final release. (It's currently in release candidate as I'm writing this comment.)

Therefore I'm not intending to make any new releases, because my attention is elsewhere at the moment and this repository is about to become redundant.

The specific change you are referring to here isn't really directly portable into the upstream version because it was a quirk of how the credentials helper protocol works and Terraform will no longer be using that protocol to implement it, but I believe the effect is the same nonetheless: Terraform will treat a missing environment variable as the absence of credentials for a host, rather than as an error in its own right.

Thanks!
